package util;

public enum TokenM {

    ADD, MULTIPLE, SUBTRACT, DIVIDE,

    BUKA_KURUNG, TUTUP_KURUNG, FACTOR, NUMERATOR, DENUMERATOR,

    COMPOSITE, SIMPLE,

    ADDER, SUBTRACTOR, ANGKA, EQUAL, EMPTY
}
